from Energy_density_spectrum import *

print("请输入sigma和epsilon的值:")
sigma = float(input())
epsilon = float(input())
data = open(f"./data_sigma={sigma}_epsilon_{epsilon}.txt","w")
data.write(f"#   sigma={sigma}    epsilon={epsilon}\n")
data.write("# k Delta_tot\n")
plt.rc('text', usetex=True)
k = np.logspace(-2,1,30)
Delta_s = spectrum_s(k, sigma,epsilon)
Delta_d = spectrum_d(k, sigma,epsilon)
for i in range(len(k)):
	data.write(f"{k[i]}  {Delta_s[i]+Delta_d[i]}\n")
data.close()
# plt.loglog(k, Delta_s,"b--",label="$\Delta^{(s)}$")
# plt.loglog(k, Delta_d,"b:",label="$\Delta^{(d)}$")
# plt.loglog(k, Delta_s+Delta_d,"r-",label="$\Delta$")
# plt.xlabel(r"$k/\tilde{\beta}$",fontsize=20)
# plt.ylabel("$\Delta$",fontsize=20)
# plt.legend(fontsize=18)
# plt.title(fr"$\sigma={sigma}$",fontsize=25)
# plt.savefig(f"../Figure/sigma={sigma}_large_k.png",dpi=1000,bbox_inches="tight")
# plt.show()
